yolo_model:

  config_file:
    name: yolov3.cfg
  weight_file:
    name: yolov3.weights
  threshold:
    value: 0.7
  detection_classes:
    names:
      - person
      - bicycle
      - car
      - motorbike
      - bus
      - truck
      - traffic light
      - stop sign
